/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pre;

import bus.BezierCurve;
import bus.BezierDraw;
import bus.BezierMove;
import bus.Canvas;
import dat.lib.ObjectIO;
import java.io.File;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author dpf
 */
public class CanvasFrame extends javax.swing.JFrame{   
    
    private final Canvas canvas;
    
    /**
     * Creates new form Graph
     * @param canvas
     */
    public CanvasFrame(Canvas canvas) {
        initComponents();
        this.canvas = canvas;
        canvasPanel.setLayout(new BoxLayout(canvasPanel,BoxLayout.Y_AXIS));
        canvasPanel.add(canvas);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileSave = new javax.swing.JMenuItem();
        fileOpen = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        fileExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuTools = new javax.swing.JMenu();
        toolsNewCurve = new javax.swing.JMenuItem();
        toolsBezierMove = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        viewAntialiasing = new javax.swing.JCheckBoxMenuItem();
        viewShowControl = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvasPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        menuFile.setText("File");

        fileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        fileNew.setText("New");
        fileNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewActionPerformed(evt);
            }
        });
        menuFile.add(fileNew);
        menuFile.add(jSeparator1);

        fileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fileSave.setText("Save As...");
        fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveActionPerformed(evt);
            }
        });
        menuFile.add(fileSave);

        fileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fileOpen.setText("Open");
        fileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenActionPerformed(evt);
            }
        });
        menuFile.add(fileOpen);
        menuFile.add(jSeparator2);

        fileExit.setText("Exit");
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        menuFile.add(fileExit);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuBar.add(menuEdit);

        menuTools.setText("Tools");

        toolsNewCurve.setText("New Bezier curve");
        toolsNewCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsNewCurveActionPerformed(evt);
            }
        });
        menuTools.add(toolsNewCurve);

        toolsBezierMove.setText("Move Bezier curve");
        toolsBezierMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsBezierMoveActionPerformed(evt);
            }
        });
        menuTools.add(toolsBezierMove);

        menuBar.add(menuTools);

        menuView.setText("View");

        viewAntialiasing.setSelected(true);
        viewAntialiasing.setText("Antialiasing");
        viewAntialiasing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAntialiasingActionPerformed(evt);
            }
        });
        menuView.add(viewAntialiasing);

        viewShowControl.setSelected(true);
        viewShowControl.setText("Show control polygon");
        viewShowControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewShowControlActionPerformed(evt);
            }
        });
        menuView.add(viewShowControl);

        menuBar.add(menuView);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolsNewCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsNewCurveActionPerformed
        canvas.setMouseAdapter(BezierDraw.getInstance(canvas).getMouseAdapter(),BezierDraw.getInstance(canvas).getCursor());
    }//GEN-LAST:event_toolsNewCurveActionPerformed

    private void fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(new JFrame());
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ObjectIO.writeObject(canvas.getShapes(), selectedFile);
        }
    }//GEN-LAST:event_fileSaveActionPerformed

    private void viewAntialiasingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAntialiasingActionPerformed
        if(viewAntialiasing.isSelected()){
            canvas.setAntialiasing(true);
        }else{
            canvas.setAntialiasing(false);
        }
        canvas.repaint();
    }//GEN-LAST:event_viewAntialiasingActionPerformed

    private void viewShowControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewShowControlActionPerformed
        if(viewShowControl.isSelected()){
            canvas.setShowControl(true);
        }else{
            canvas.setShowControl(false);
        }
        canvas.repaint();
    }//GEN-LAST:event_viewShowControlActionPerformed

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    private void fileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(new JFrame());
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            canvas.loadShapes((List<BezierCurve>)(ObjectIO.readObject(selectedFile)));
        }
        canvas.repaint();
    }//GEN-LAST:event_fileOpenActionPerformed

    private void fileNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewActionPerformed
        canvas.init();
        canvas.repaint();
    }//GEN-LAST:event_fileNewActionPerformed

    private void toolsBezierMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsBezierMoveActionPerformed
        canvas.setMouseAdapter(BezierMove.getInstance(canvas).getMouseAdapter(),BezierDraw.getInstance(canvas).getCursor());
    }//GEN-LAST:event_toolsBezierMoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileNew;
    private javax.swing.JMenuItem fileOpen;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem toolsBezierMove;
    private javax.swing.JMenuItem toolsNewCurve;
    private javax.swing.JCheckBoxMenuItem viewAntialiasing;
    private javax.swing.JCheckBoxMenuItem viewShowControl;
    // End of variables declaration//GEN-END:variables

}
